#Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.

s = ("CCTAAGCGCTAGAAGACAATATATTGGGTAGAGCAGGCAAACCCCAACGATGCCCGGTGCCCGGGGCGTGCTATCCATCAGGTGTGCTCCCGGTATCTCTGTGGCGAGTACCCCATCCGGTAAAAACGTAGGATTGATTCAAGTTTCGCACGGGGCCTTACGACTCCTTGGGCGCACTACACGATATCAAGTAGGTCTGACGATTTCTAAATTGGAGTAAACTTCGACACGATCGGGTCTGTCGTTTAGGAGGAGACAGATTCGTCCGGCAGTGCCCGTTTGACATGGCTTCGTTTTGTTCAACTTGACTTGTAACACGCGTCCGAACCATTCTTAAGGCTGGGCTTGTAGGGGTTGCCACCAGGCATGAGCCAATGCTCCTTTGGCTAACTAAGGCTTTATGAAAACGGCTCATGAGGACATGGCCGTTAATCCCTCAGTCTGCTTCCTCCGGGGCAATGTCTCGATAATAACGCAGGCTGCGTATCCCAACGGATGTTCTACATCCTGTGGTCATATTTCTAGGAGGCCGTACACTGCTGGTAGGTCTGCCATAGATCCACAGTGAGTACTGGTCTACCCTGAGCGTTCCTGAGGCATTGGCGTTATCAGGCTCTCCAACTCCTGGCCTTACACTTCAAGGACTGTAGGCACTATGTTTTCGGGAGTTGAGCGTTTGATGAGGCAGGGATGTATATTATGGTCATTTGTTTCGGACGTTCTCATTACGAGAATCAAATGGTTCCTTTTCTATGAGACGCCGTGGGTGTTCGCTTCCAGAAAAGAATTTGGGACAAATCCATGAAAGC")
numberof_A = 0
numberof_C = 0
numberof_G = 0
numberof_T = 0

for letter in s:
    if letter == "A":
        numberof_A = numberof_A + 1
    if letter == "C":
        numberof_C = numberof_C + 1
    if letter == "G":
        numberof_G = numberof_G + 1
    if letter == "T":
        numberof_T = numberof_T + 1

print(numberof_A," ", numberof_C, " ", numberof_G, " ", numberof_T)